export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCEFULL = "LOGIN_SUCCEFULL";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SET_USER_IN_STORE = "SET_USER_IN_STORE";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESFULL = "LOGOUT_USER_SUCCESFULL";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";
