export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const PUT_ALL_PRODUCTS = "PUT_ALL_PRODUCTS";
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const PUT_TO_BASKET = "PUT_TO_BASKET";
export const GET_ALL_BASKET = "GET_ALL_BASKET";
export const PUT_ALL_BASKET = "PUT_ALL_BASKET";